### PR TITLE
Fix PitchingPost BAOpp

### PR DESCRIPTION
**Pull request by wclark17**
I had trouble loading this file into postrgesql because of the baopp column.
This file now loads

### CODE REVIEW

**Comment by tturocy** [comment]
If I'm understanding correctly, the change seems to be to set BAopp to zero where it is currently null -- which isn't correct?  Or am I mis-reading the diff?

**Comment by wclark17** [comment]
That is correct.
There was also a line that had a "-" for baopp, and that caused a problem.

I didn't go back and play with the loads, so the nulls may have been fine.
I can go back and check if you want to hold off on the pull request.

Bill

**Comment by tturocy** [comment]
Well, certainly, changing NULLs to zeroes isn't acceptable!

A change set should be absolutely minimal - only what is meant to be being changed should change.  There seem to be extraneous changes.  It looks like you might have re-dumped this from your database -- if so that's not a best practice because it'll introduce those formatting changes, which obscures the content changes, so is counter indicated.

In terms of changing a field, I don't consider that a particular tool had problems with file to be enough of a justification per se to make a change on its own. If it is a question of following a particular convention consistently through the files, then that is a stronger argument (and may require revisions to other files as well for consistency).

**Comment by wclark17** [comment]
Makes sense to me.

The only change I think is necessary,  and to make things consistent is to
change where there was a '-' in a field and make it a NULL.

I'll redo to pull request with that change and hopefully avoid any format
changes.

Thanks Bill

**Pull request closed without merging**
