### PR TITLE
Missing PitchingPost ERAs. Missing Hal Dues Year.

### PR DESCRIPTION
**Pull request by jasonmm**
Added missing ERA values in PitchingPost. #64 
Added missing year for Hal Dues. #49

### CODE REVIEW

**Comment by jasonmm** [comment]
Any suggestions on something further I need do to get this pull request accepted?

**Comment by tturocy** [comment]
These tables are built from scripts, and as such it does not make sense to accept downstream pull requests (as any changes get overwritten in the next build).

It is of course completely fine to patch these downstream in your own repository if your needs require them.

**Comment by jasonmm** [comment]
Thanks for the explanation! Are the scripts that build the tables available?

**Comment by tturocy** [comment]
No, they aren't; they wouldn't do anyone much good as they build from proprietary datasets!

**Pull request closed without merging**
